### PR TITLE
Polyline & Polygon support

### PR DESCRIPTION
**Pull request by LJaraCastillo**
* Polyline support
* Polyline tap event support
* Polygon support
* Hole support for polygons
* Polygon tap event support
* Updated gradle dependencies
* Updated example
* Added examples of polylines and polygons in README.md

### CODE REVIEW

**Comment by diogoribeiro23** [comment]
You are awesome! 
Do you have any thoughts on the app bar customization that you wanna share? :)

**Comment by LJaraCastillo** [comment]
For now it works well and i don't have the need to modify it yet. Maybe could exist an attribute to hide it so the map could be shown fullscreen.

**Comment by matthewtsmith** [comment]
@LJaraCastillo Thanks for the PR. I've been pretty overwhelmed with work lately but I plan on catching up on PRs this weekend and getting a new version out.

**Comment by LJaraCastillo** [comment]
@matthewtsmith No problem, keep up the good work.

**Review by matthewtsmith — APPROVED** [review]

**Comment by diogoribeiro23** [comment]
@LJaraCastillo is it too much work to also include encoded polylines? 
Thank you for improving this plugin so much :D

**Comment by LJaraCastillo** [comment]
@diogoribeiro23 hmmm i don't know exactly how that works. Could you explain me what exactly do you need about the encoding?

**Comment by diogoribeiro23** [comment]
@LJaraCastillo this: 
https://developers.google.com/maps/documentation/utilities/polylinealgorithm
google maps can receive a polyline made by an array of points or by an encoded polyline ^.
here is the method to decode them: 
http://jeffreysambells.com/2010/05/27/decoding-polylines-from-google-maps-direction-api-with-java
Do you understand? :)

**Comment by diogoribeiro23** [comment]
maybe it is easier to do it outside the plugin?

**Comment by LJaraCastillo** [comment]
Let me see if i understand. You want to use the plugin (Flutter side) and add this string encoded points instead of the traditional points and decoded it on Kotlin to show it on the map?

**Comment by diogoribeiro23** [comment]
i want it to be able to receive that string with the encoded points so it can decode it and show them on the map.
It just needs to have the decode function at the beginning because it returns a list of locations and after that you can just send it to the available methods because after that it's exactly the same. (I think)

**Comment by diogoribeiro23** [comment]
it should be the same method as adding a single polyline, but if it receives a string instead of a list it runs the decode function before anything else.

**Comment by LJaraCastillo** [comment]
I understand, is not hard. I will make some time to work on this on my free time, most probably the next week.

**Comment by diogoribeiro23** [comment]
Thank you so much! :D 
In the mean time ill be using the decode function before calling the plugin. I'll be paying attention!

**Comment by diogoribeiro23** [comment]
Hello again @LJaraCastillo! Just noticed that in this merge, in Android when u have a polyline and you call zoomtofit() it counts the polyline as a 'marker' to fit, but in iOS this doesn't happen. Could you take a look at that?

**Pull request merged**
